name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  RUST_BACKTRACE: full

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "windows-latest"
          - os: "macos-latest"
          - os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update --no-self-update stable

      - name: Build
        run: cargo build --locked --verbose
